services:
  obs-mock:
    build:
      context: .
      dockerfile: Dockerfiles.d/obs-mock/Dockerfile
      args:
        GID: "${GID:-1000}"
        UID: "${UID:-1000}"
    working_dir: /workspace/obs-mock
    volumes:
      - .:/workspace
    ports:
      - "4455:4455"
    command: cargo watch -x run
    tty: true
    stdin_open: true
